plugins {
    id 'java'
}

group = 'org.markski.blocklog'
version = '0.3.0'


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven {
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.65-beta'
    compileOnly 'org.xerial:sqlite-jdbc:3.53.2.0'
}

tasks.jar {
    archiveBaseName.set('blocklog')
    archiveVersion.set(version)
}

test {
    useJUnitPlatform()
}
