name: Blocklog
main: org.markski.blocklog.Main
version: 0.0.1
api-version: 1.20
description: A lightweight block interaction logging plugin.
authors: [ "Markski" ]

commands:
  bkl:
    description: Shows info about the block you're looking at.
    usage: /bkl
