name: BlockLog
main: org.markski.blocklog.Main
version: 0.3.0
api-version: '26.2'
description: A lightweight block interaction logging plugin.
authors: [ "Markski" ]
libraries:
  - org.xerial:sqlite-jdbc:3.53.2.0

commands:
  bkl:
    description: All BlockLog related commands.
    permission: blocklog.use
    permission-message: You do not have permission to use BlockLog.
permissions:
  blocklog.use:
    description: Allows using /bkl base command.
    default: op
  blocklog.inspect:
    description: Allows using /bkl i (inspect mode).
    default: op
  blocklog.rollback:
    description: Allows using /bkl rollback.
    default: op
