name: BlockLog
main: org.markski.blocklog.Main
version: 0.2.0
version: 0.3.0
api-version: 1.20
description: A lightweight block interaction logging plugin.
authors: [ "Markski" ]

commands:
  bkl:
    description: All BlockLog related commands.
permissions:
  blocklog.use:
    description: Allows using /bkl base command.
    default: op
  blocklog.inspect:
    description: Allows using /bkl i (inspect mode).
    default: op
  blocklog.rollback:
    description: Allows using /bkl rollback.
    default: op
    permission: blocklog.use
    permission-message: "§cYou don't have permission to use BlockLog commands."
